### ISSUE TITLE
New function flag, call functions from functions and unpack function arguments

### ISSUE THREAD

**Issue by cairdcoinheringaahing** [cairdcoinheringaahing/AddPlusPlus#5]
Idea for a new function flag: `!`
Pushes the values to the stack as a list. For example:

    D,example,@@@!,h
    $example>10>20>30

would print

    [[10, 20, 30]]

Acts as a shortcut of `B]`

---

An additional (later) idea would be to have a way of calling functions from within a function

For example

    D,main,@@,{aux}2*
    D,aux,@@,10++
    $main>?>?
    O

Would be the same as 

    D,main,@,2*
    D,aux,@@,10++
    $aux>?>?
    $main>x
    O

---

Also, a way of taking input all together (`_`), then allowing that to be given as a function argument that would unpack that as function arguments.

An example:

    D,test,?!,B+
    $test>_

Would be very difficult to replicate, depending on the number of arguments possible.

**Comment by TheHoldingPen** [comment]
Possible addition: lambda functions. The number of arguments is determined by the number of arguments given. Mainly used for some golfing competitions. For example, rather than

    D,f,@@@!,++

The code could be written as

    L!,++

This would be stored as `{'lambda 1':'++'}` and would be called as

    $lambda 1>arg>arg

Flags would come directly before the `,` and directly after the `L`.

**Comment by cairdcoinheringaahing** [comment]
Adding lambdas could lead to some interesting solutions, so that would definitely be worth adding. So, I think the checklist would look something line this:

1. Add the `!` list argument flag
2. Add the `_` function argument
3. Add lambda functions
  3.1. Without flag functionality
  3.2. With flag support
4. Allowing referencing to other functions
  4.1. Only referencing names functions
  4.2. Referencing lambdas as well
  4.3. Allowing lambdas to reference other functions
  4.4. Golfed form of referencing lambdas (`]` pops a number and runs that lambda)
5. Adding support for another stack
6. Adding support for multiple accumulators

I'll close this issue when all are added (it may take a while)

**Comment by cairdcoinheringaahing** [comment]
With the latest pull taken care of, the checklist currently looks like this:

1. <s>Add the ! list argument flag</s>
2. <s>Add the _ function argument</s>
3. <s>Add lambda functions</s>
 3.1. <s>Without flag functionality</s>
 3.2. <s>With flag support</s>
4. Allowing referencing to other functions
 4.1. Only referencing named functions
 4.2. Referencing lambdas as well
 4.3. Allowing lambdas to reference other functions
 4.4. Golfed form of referencing lambdas (] pops a number and runs that lambda)
5. Adding support for another stack
6. Adding support for multiple accumulators

**Comment by cairdcoinheringaahing** [comment]
I'm removing 6. from the check list. And have completed everything else, so I am closing this issue once I've uploaded the code.
